/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cuentaluz;

import java.awt.Color;
import java.math.BigDecimal;

import java.math.RoundingMode;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.mycompany.cuentaluz.conexion.Conexion;
import com.mycompany.cuentaluz.utilidades.BordeRedondeado;
import com.mycompany.cuentaluz.utilidades.BottomBorder;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;

/**
 *
 * @author ALEX
 */
public class Principal extends javax.swing.JFrame {
    int MedAnterior = 0;// traer de la base de datos
    Conexion con;
    double total = 0;

    /**
     * Creates new form Principal
     */
    public Principal() {
        ImageIcon icono = new ImageIcon(Principal.class.getResource("/imgs/icono.png"));
        setIconImage(icono.getImage());
        initComponents();
        CambiosInciales();

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPrincipal = new javax.swing.JTextField();
        txtSecundario = new javax.swing.JTextField();
        lblFecha = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SECUNDARIO:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PRINCIPAL:");

        txtPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblFecha.setFont(new java.awt.Font("Dialog", 0, 19)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));

        txtTotal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtTotal.setText("TOTAL:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void CambiosInciales() {

        txtPrincipal.setBorder(new BottomBorder(1, new Color(55, 55, 56, ABORT)));
        txtSecundario.setBorder(new BottomBorder(1, new Color(55, 55, 56, ABORT)));
        BordeRedondeado btnCalcular = new BordeRedondeado("CALCULAR", 35);
        btnCalcular.setBounds(15, 140, 270, 40);
        btnCalcular.setOpaque(true);
        btnCalcular.setBackground(new Color(26, 66, 99));
        btnCalcular.setForeground(Color.white);
        btnCalcular.setHorizontalAlignment(SwingConstants.CENTER);
        Font nuevaFuente = new Font("Franklin Gothic Demi", Font.ITALIC, 25);
        btnCalcular.setFont(nuevaFuente);
        btnCalcular.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPanel1.add(btnCalcular);
        btnCalcular.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                btnCalcular.setBackground(Color.BLACK);

            }

            @Override
            public void mouseExited(MouseEvent e) {
                btnCalcular.setBackground(new Color(26, 66, 99));
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    String principal = txtPrincipal.getText();
                    String secundario = txtSecundario.getText();
                    if (principal.length() == 4 && secundario.length() == 5) {
                        if (calcular()) {
                            txtTotal.setText("TOTAL: " + total + "0");
                        } else {
                            txtTotal.setText("TOTAL: " + total + "0");
                            int i = JOptionPane.showConfirmDialog(null,
                                    "ya existe un registro de este mes.\nDesea ver los registros?", "ERROR!", 0,
                                    JOptionPane.OK_CANCEL_OPTION, null);
                            if (i == 0) {
                                new ListaDatos().setVisible(true);
                            } else {
                                System.out.println("no quiso abrir los registros");
                            }
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "validar los siguientes campos:\n-En el campo principal son 4 digitos\n-En el campo secundario son 5 digitos", "ERROR!", JOptionPane.ERROR_MESSAGE);
                    }

                }
            }

        });

        con = new Conexion();
        lblLogo.setIcon(CrearImg(new ImageIcon(Principal.class.getResource("/imgs/logoLuz.png")), lblLogo));
        lblFecha.setEnabled(false);
        txtTotal.setEnabled(false);
        LocalDate fechaActual = LocalDate.now();
        String fecha = fechaActual.format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        lblFecha.setText(fecha);
        MedAnterior = con.MedicionAnterior(lblFecha.getText());

    }

    private boolean calcular() {

        int MedActualPrincipal = Integer.parseInt(txtPrincipal.getText());
        System.err.println("Principal: " + MedActualPrincipal);
        double MedActualSecundario = Double.parseDouble(txtSecundario.getText());
        System.err.println("Secundario: " + MedActualSecundario);
        double DifMediciones = (MedActualSecundario - MedAnterior) / 10;
        System.err.println("Diferencia mediciones Jose: " + DifMediciones);
        double CargPrincipal = (int) (MedActualPrincipal + (0.31 * MedActualPrincipal));
        System.err.println("principal+31%: " + CargPrincipal);
        double Total = (CargPrincipal * DifMediciones) / 10000;
        BigDecimal TotalRedondeado = new BigDecimal(Total);
        TotalRedondeado = TotalRedondeado.setScale(1, RoundingMode.HALF_UP);
        System.err.println("TOTAL: " + Total);
        boolean validar = con.IngresarDatos(lblFecha.getText(), (int) MedActualPrincipal, (int) MedActualSecundario,
                TotalRedondeado.doubleValue());
        if (validar) {
            total = TotalRedondeado.doubleValue();
        }
        return validar;
    }

    /**
     * 
     * @param url        ruta de la imagen o la imagen
     * @param contenedor Jlabel que va a contener la imagen
     * @return returna la imagen ajustada al tamaño del Jlabel
     */
    private Icon CrearImg(ImageIcon img, JLabel contenedor) {

        Icon icono = new ImageIcon(
                img.getImage().getScaledInstance(contenedor.getWidth() + 12, contenedor.getHeight() + 100,
                        contenedor.getWidth()));
        return icono;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblFecha;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtPrincipal;
    private javax.swing.JTextField txtSecundario;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
